// Section metadata for sidebar subsection navigation
export interface SectionMeta {
  id: string
  title: string
}

export const chapterSections: Record<string, SectionMeta[]> = {
  "1": [
    { id: "1.1", title: "一维数学" },
    { id: "1.2", title: "二维笛卡尔空间" },
    { id: "1.3", title: "三维笛卡尔空间" },
    { id: "1.4", title: "坐标系在实际应用中的考量" },
    { id: "1.5", title: "距离公式与重要恒等式" },
  ],
  "2": [
    { id: "2.1", title: "向量——数学定义" },
    { id: "2.2", title: "向量——几何定义" },
    { id: "2.3", title: "向量与点的区别" },
    { id: "2.4", title: "用笛卡尔坐标表示向量" },
    { id: "2.5", title: "向量的取反" },
    { id: "2.6", title: "向量与标量的乘法" },
    { id: "2.7", title: "向量的加法与减法" },
    { id: "2.8", title: "向量的模长" },
    { id: "2.9", title: "单位向量与归一化" },
    { id: "2.10", title: "使用向量计算距离" },
    { id: "2.11", title: "向量的点积" },
    { id: "2.12", title: "向量的叉积" },
    { id: "2.13", title: "重要线性代数恒等式" },
  ],
  "3": [
    { id: "3.1", title: "为什么需要多重坐标空间？" },
    { id: "3.2", title: "游戏中的常用坐标空间" },
    { id: "3.3", title: "坐标空间变换" },
    { id: "3.4", title: "嵌套坐标空间" },
    { id: "3.5", title: "指定坐标空间" },
    { id: "3.6", title: "基向量与坐标空间" },
  ],
  "4": [
    { id: "4.1", title: "矩阵——数学定义" },
    { id: "4.2", title: "方阵与对角矩阵" },
    { id: "4.3", title: "向量作为矩阵" },
    { id: "4.4", title: "矩阵的转置" },
    { id: "4.5", title: "矩阵与标量的乘法" },
    { id: "4.6", title: "矩阵与矩阵的乘法" },
    { id: "4.7", title: "矩阵与向量的乘法" },
    { id: "4.8", title: "矩阵的几何解释" },
    { id: "4.9", title: "矩阵与线性变换" },
    { id: "4.10", title: "矩阵运算总结" },
  ],
  "5": [
    { id: "5.1", title: "旋转矩阵" },
    { id: "5.2", title: "缩放矩阵" },
    { id: "5.3", title: "投影矩阵" },
    { id: "5.4", title: "反射矩阵" },
    { id: "5.5", title: "剪切矩阵" },
    { id: "5.6", title: "变换的组合" },
    { id: "5.7", title: "变换的分类" },
  ],
  "6": [
    { id: "6.1", title: "行列式" },
    { id: "6.2", title: "逆矩阵" },
    { id: "6.3", title: "正交矩阵" },
    { id: "6.4", title: "齐次坐标" },
    { id: "6.5", title: "4×4 平移矩阵" },
    { id: "6.6", title: "透视投影" },
    { id: "6.7", title: "正交投影" },
    { id: "6.8", title: "屏幕空间变换" },
    { id: "6.9", title: "完整变换管线回顾" },
  ],
  "7": [
    { id: "7.1", title: "2D 极坐标" },
    { id: "7.2", title: "为什么使用极坐标？" },
    { id: "7.3", title: "3D 球面坐标" },
    { id: "7.4", title: "3D 柱面坐标" },
    { id: "7.5", title: "坐标系对比与选择" },
  ],
  "8": [
    { id: "8.1", title: "旋转的复杂性" },
    { id: "8.2", title: "欧拉角" },
    { id: "8.3", title: "轴-角表示" },
    { id: "8.4", title: "四元数" },
    { id: "8.5", title: "旋转方法对比与选择" },
    { id: "8.6", title: "各表示间的转换" },
  ],
  "9": [
    { id: "9.1", title: "表示方法" },
    { id: "9.2", title: "直线与射线" },
    { id: "9.3", title: "球体与包围球" },
    { id: "9.4", title: "AABB 包围盒" },
    { id: "9.5", title: "OBB 有向包围盒" },
    { id: "9.6", title: "平面" },
    { id: "9.7", title: "三角形" },
    { id: "9.8", title: "视锥体" },
    { id: "9.9", title: "多边形" },
  ],
  "10": [
    { id: "10.1", title: "渲染管线概述" },
    { id: "10.2", title: "光照模型" },
    { id: "10.3", title: "纹理映射" },
    { id: "10.4", title: "骨骼动画" },
    { id: "10.5", title: "阴影映射" },
  ],
  "11": [
    { id: "11.1", title: "运动学基础" },
    { id: "11.2", title: "导数与积分" },
    { id: "11.3", title: "匀速与匀加速运动" },
    { id: "11.4", title: "圆周运动" },
  ],
  "12": [
    { id: "12.1", title: "牛顿定律" },
    { id: "12.2", title: "动量与冲量" },
    { id: "12.3", title: "旋转动力学" },
    { id: "12.4", title: "刚体模拟" },
  ],
  "13": [
    { id: "13.1", title: "参数多项式曲线" },
    { id: "13.2", title: "三次 Hermite 曲线" },
    { id: "13.3", title: "Bezier 曲线" },
    { id: "13.4", title: "Catmull-Rom 样条" },
    { id: "13.5", title: "弧长参数化" },
    { id: "13.6", title: "Frenet 标架" },
    { id: "13.7", title: "连续性详解" },
  ],
  "14": [
    { id: "14.1", title: "后续学习方向" },
    { id: "14.2", title: "附录A: 几何测试" },
    { id: "14.3", title: "附录B: 习题答案" },
    { id: "14.4", title: "致谢" },
  ],
}